config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  get 'schedules/new'
  get 'schedules/edit'
  get 'schedules/show'
  get 'schedules/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
     validates :title, presence: true
     validates :start,  presence: true
     validates :end, presence: true
     validate :start_end_check
     validate :startday
     
     def start_end_check
        return if self.start.blank?
        return if self.end.blank?
        errors.add(:end, "は開始日より前は登録できません。") unless self.start < self.end 
     end
     
     def startday
       return if self.start.blank?
       errors.add(:start, "は今日以降の日付を選択してください") if start < Date.today
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
     @schedules = Schedule.all
  end
  
  def new
     @schedule = Schedule.new
  end
 
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title,:start,:end,:allday,:memo)) 
    if @schedule.save
      redirect_to :schedules
    else
      render "new"
    end
  end
 
  def show
    @schedule = Schedule.find(params[:id])
  end
 
  def edit
    @schedule = Schedule.find(params[:id])
  end
 
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title,:start,:end,:allday,:memo))
      redirect_to :schedules
    else
      render "edit"
    end
  end
 
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to :schedules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
    
  </body>
</html>

app/views/schedules/edit.html.erb
<h3>スケジュール編集</h3>
<%= render "shared/error", obj: @schedule %>
<%= form_for @schedule do |f| %>
<table>
    <tr>
            <th><%= f.label :title,"タイトル"%></th>
            <td><%= f.text_field :title %></td>
        </tr>
        <tr>
            <th><%= f.label :start,"開始日"%></th>
            <td><%= f.text_field :start %></td>
        </tr>
        <tr>
            <th><%= f.label :end,"終了日"%></th>
            <td><%= f.text_field :end %></td>
        </tr>
        <tr>
            <th><%= f.label :allday,"終日"%></th>
            <td><%= f.check_box :allday %></br>
                終日の場合はチェックを入れます</td>
        </tr>
        <tr>
            <th><%= f.label :memo,"スケジュールメモ"%></th>
            <td><%= f.text_field :memo %></td>
        </tr>
</table>

<div>
     <ul class ="choice">
       <li><%= f.submit "編集を完了する" %></li>
       <li><%= link_to "スケジュール情報一覧に戻る", :schedules,class:"link" %></li>
     </ul>
</div>

<footer>
    <h1>現在の日時:<%= Time.now.strftime("%Y年%m月%d日") %></h1>
</footer>

<% end %>

app/views/schedules/index.html.erb
<h3>スケジュール一覧</h3>
<table>
 <tr>
  <th>ID</th>
  <th>タイトル</th>
  <th>開始日</th>
  <th>終了日</th>
  <th>終日</th>
  <th>スケジュール更新日時</th>
  <th>確認</th>
  <th>編集</th>
  <th>削除</th>
 </tr>


<tbody>
 <% @schedules.each do |schedule| %>
 <tr>
  <td><%= schedule.id %></td>
  <td><%= schedule.title %></td>
  <td><%= schedule.start %></td>
  <td><%= schedule.end %></td>
  <% if schedule.allday == true then %>
  <td>○</td>
  <% else %>
  <td> </td>
  <% end %>
  <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
  <td><%= link_to "確認",schedule,class:"link" %></td>
  <td><%= link_to "編集",[:edit,schedule],class:"link"%></td>
  <td>
  <%= link_to "削除", schedule, method: :delete, data: { confirm: "本当に削除しますか？" },class:"link" %>
  </td>
 </tr>
 <% end %>
</tbody>
</table>

<p><%= link_to "スケジュール新規登録",:new_schedule, class:"link" %></p>

<footer>
 <h1>現在の日時:<%= Time.now.strftime("%Y年%m月%d日") %> スケジュールの合計:<%= Schedule.count %></h1>
</footer>

app/views/schedules/new.html.erb
<h3>スケジュール新規作成</h3>
 <%= render "shared/error", obj: @schedule %>
 <%= form_for @schedule do |f| %>
    <table>
        <tr>
            <th><%= f.label :title,"タイトル"%></th>
            <td><%= f.text_field :title %></td>
        </tr>
        <tr>
            <th><%= f.label :start,"開始日"%></th>
            <td><%= f.date_field :start %></td>
        </tr>
        <tr>
            <th><%= f.label :end,"終了日"%></th>
            <td><%= f.date_field :end %></td>
        </tr>
        <tr>
            <th><%= f.label :allday,"終日"%></th>
            <td><%= f.check_box :allday %></br>
                終日の場合はチェックを入れます
            </td>
        </tr>
        <tr>
            <th><%= f.label :memo,"スケジュールメモ"%></th>
            <td><%= f.text_field :memo %></td>
        </tr>
    </table>
    
    <div>
     <ul class = "choice">
       <li><%= f.submit "スケジュールを新規登録する"%></li>
       <li><%= link_to "スケジュール一覧に戻る",:schedules,class:"link"%></li>
     </ul>
   </div>
   
    <footer>
      <h1>現在の日時:<%= Time.now.strftime("%Y年%m月%d日") %></h1>
    </footer>
    
<% end %>

app/views/schedules/show.html.erb
<h3>スケジュール詳細</h3>

<table>
   <tr>
     <th>タイトル</th>
     <td><%= @schedule.title %></td>
   </tr>
   <tr>
     <th>開始日</th>
     <td><%= @schedule.start %></td>
   </tr>
   <tr>
     <th>終了日</th>
     <td><%= @schedule.end %></td>
   </tr>
   <tr>
      <th>終日</th>
       <% if @schedule.allday == true then %>
       <td>○</td>
       <% else %>
       <td> </td>
       <% end %>
   </tr>
   <tr>
      <th>スケジュールメモ</th>
      <td><%= @schedule.memo %></td>
   </tr>
 </table>
 
 <div>
   <ul class="choice">
     <li><%= link_to "スケジュール情報一覧に戻る", :schedules, class:"link" %></li>
     <li><%= link_to "スケジュールを編集する", edit_schedule_path, class:"link" %></li>
     <li><%= link_to "スケジュールを削除", schedule_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class:"link" %></li>
   </ul>
 </div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
   <% obj.errors.full_messages.each do |message| %>
     <ul>
       <li><%= message %></li>
     </ul>
   <% end %>
 <% end %>